### ISSUE TITLE
Ignore Dependabot types- patch updates

### ISSUE THREAD

**Issue by josh** [josh/overcast-data#17]
```yaml
ignore:
 - dependency-name: "types-*"
   update-types: ["version-update:semver-patch"]
```
